USE [EBOARDING_DELHI]
GO
/****** Object:  StoredProcedure [dbo].[GETBGLASTUPDTIME_DFMD]    Script Date: 17-10-2024 12:45:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
 
create PROCEDURE [dbo].[GETBGLASTUPDTIME_DFMD]
 
AS
 
BEGIN
    DECLARE @TIMEDIFF INT;
	DECLARE @STATUS VARCHAR(15);
	    DECLARE @LATESTREC VARCHAR(50);
 
    SET NOCOUNT ON;
 
	select top 1  @LATESTREC = IIF(MAX(REC_CREATED_TIME) is null, MAX(GATEReplyUpdatedTime), MAX(REC_CREATED_TIME) )
 
	from FLOWCONTROLTAB(nolock)
 
	 SET @TIMEDIFF = DATEDIFF(SECOND, @LATESTREC, GETDATE());
    IF (@TIMEDIFF > 90 or @LATESTREC is  null)
 
        SET @STATUS = 'FAIL';
 
    ELSE
 
        SET @STATUS = 'PASS';
 
	    SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS identity_column, @LATESTREC AS Latest_Record, @STATUS AS Status;
 

	END

